# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_educationalchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalchannel',
            name='fieldOfInterests',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
